"""changes in post table

Revision ID: a965607baf75
Revises: 076fa292d8fd
Create Date: 2026-06-02 19:26:01.667633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a965607baf75'
down_revision = '076fa292d8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), server_default='draft', nullable=False))
        batch_op.add_column(sa.Column('views_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('views_count')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
