"""added description field to post

Revision ID: ea14fa0e7767
Revises: 77247c2333b7
Create Date: 2026-05-12 19:46:49.128566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea14fa0e7767'
down_revision = '77247c2333b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('courses',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('students',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('profiles',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('user_id')
    # )
    # op.create_table('student_course',
    # sa.Column('student_id', sa.Integer(), nullable=False),
    # sa.Column('course_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    # sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    # sa.PrimaryKeyConstraint('student_id', 'course_id')
    # )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.drop_table('student_course')
    op.drop_table('profiles')
    op.drop_table('students')
    op.drop_table('courses')
    # ### end Alembic commands ###
